name: cleanup

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: read
  statuses: read

jobs:
  ci:
    runs-on: ubuntu-latest
    container: ghcr.io/macedogm/rancher-obs-image:latest
    steps:
      # This is a workaround needed for the .git dir to be available inside the container
      # See https://github.com/actions/checkout/issues/335
      - name: Configuring Git
        run: git config --global --add safe.directory $(pwd)

      - uses: actions/checkout@v4

      - name: Deleting leftover branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --search "is:closed is:pr" \
                     --json headRefName         \
                     --jq ".[].headRefName" | sort -u > closed_branches.txt
          gh pr list  --search "is:open is:pr" \
                      --json headRefName       \
                      --jq ".[].headRefName" | sort -u > open_branches.txt
          for branch in $(comm -23 closed_branches.txt open_branches.txt); do
            if (git ls-remote --exit-code --heads origin "$branch"); then
              echo "Deleting leftover branch - $branch";
              git push origin --delete "$branch";
            fi
          done

      - name: Configuring OSC
        env:
          OBS_USER: ${{ secrets.OBS_USER }}
          OBS_PASS: ${{ secrets.OBS_PASS }}
        run: |
          mkdir -m 700 -p "${HOME}/.config/osc"
          sed "s/OBS_USER/$OBS_USER/;s/OBS_PASS/$OBS_PASS/" config/oscrc > "${HOME}/.config/osc/oscrc"
          chmod 600 "${HOME}/.config/osc/oscrc"

#           osc ls home:gmacedo:rancher:devel:deps
      - name: Deleting leftover packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --search "is:closed is:pr" \
                     --json number \
                     --jq ".[].number" | sort -u  > closed_prs.txt
          osc ls "home:gmacedo:rancher:devel:deps" > packages.txt
          for pr in $(cat closed_prs.txt); do
            for pkg in $(grep -e "-pr_${pr}$" packages.txt); do
              echo "Deleting leftover package - $pkg"
            done
          done

      - name: Removing OSC config
        run: rm -rf "${HOME}/.config/osc/oscrc" .osc

