name: obs-build-pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
      # This is a workaround needed for the .git dir to be available inside the container
      # See https://github.com/actions/checkout/issues/335
      - name: Installing Git
        run: |
          zypper in -y git-core
          git config --global --add safe.directory $(pwd)

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          clean: false

      - name: Installing OSC
        run: |
          zypper in -y git-core python311-packaging obs-service-go_modules obs-service-recompress obs-service-set_version obs-service-tar_scm osc

      - name: Configuring OSC
        env:
          OBS_USER: ${{ secrets.OBS_USER }}
          OBS_PASS: ${{ secrets.OBS_PASS }}
        run: |
          mkdir -m 700 -p "${HOME}/.config/osc"
          sed "s/OBS_USER/$OBS_USER/;s/OBS_PASS/$OBS_PASS/" rancher/oscrc > "${HOME}/.config/osc/oscrc"
          chmod 600 "${HOME}/.config/osc/oscrc"

      - name: Building packages
        run: ./scripts/obs_build_packages.sh

      - name: Removing OSC config
        run: rm -rf .oscrc .osc

